### ISSUE TITLE
异步通信日历不能实时加载数据问题

### ISSUE THREAD

**Issue by yajun818** [dengshiwei/CalendarComponent#10]
我用的新版的CircleCalendarView控件，在Activity的onCreate中我需要通过读取当月的数据将本月的数据加载到日历上边，我使用的AsyncTask，但是发现日历加载完之后日期上并没有数据，只有随便点击一个日期后数据才会加载出来。AsyncTask类中onPostExecute方法的异步加载核心代码如下：

```
                    for(int i=0;i<arr.length();i++)
                    {
                        JSONObject temp = (JSONObject) arr.get(i);
                        String sDay=temp.getString("day");
                        String sRecord=temp.getString("record");//获得要加载的数据
                        list.add(new CalendarInfo(iYear,iMonth,Integer.parseInt(sDay),sRecord,1));      
                    }
                    circleCalendarView = (CircleCalendarView) findViewById(R.id.circleMonthView);
                    circleCalendarView.setCalendarInfos(list);
```

至此应该会从后台读取到数据并填充在日历上的啊，为何日历上空白的只有点击某一天时才能显示出来？
期待您的解惑！

**Comment by andoter0501** [comment]
好的，多谢你的反馈，我会验证后给予修改。

**Comment by yajun818** [comment]
但是除了这种异步网络操作的不能实时加载数据，普通的事务是可以加载的，比如在onCreate中添加
**list.add(new CalendarInfo(iYear,iMonth,Integer.parseInt(sDay),"test",1));
circleCalendarView = (CircleCalendarView) findViewById(R.id.circleMonthView);
                    circleCalendarView.setCalendarInfos(list);**
这样在选择的日期上会出现“test”的，但是异步网络读取数据就不行

**Comment by wdp1990821** [comment]
请问有解决办法了吗？急求。。

**Comment by andoter0501** [comment]
@yajun818 @wdp1990821 已经修改了，更改文件是MonthView，可以查看下。

**Comment by wdp1990821** [comment]
谢谢！
