### ISSUE TITLE
怎么设置某一段日期不可以选择呢 

### ISSUE THREAD

**Issue by SomnusWu** [dengshiwei/CalendarComponent#15]
只有规定的时间段 可以选择 其他的就变灰 不可选

**Comment by andoter0501** [comment]
现在是不具备这样的能力了，除非你自己定制。后续我需要完善补充类似的需求吧

**Comment by Lsy1992** [comment]
期待您的更新。。像订票、订房日历那种效果的

**Comment by SomnusWu** [comment]
能帮忙写写吗  急~~~  

ths

**Comment by SomnusWu** [comment]
大大给点思路  。  （只有规定的时间段 可以选择 ，  其他的就变灰 不可选）

**Comment by andoter0501** [comment]
在绘制日期的时候，就是在drawText的方法中，对参数的日期进行比较，如果在你的绘制要求范围内，你就进行绘制，如果不在范围内就绘制灰色，通过设置画笔颜色进行设置。

**Comment by SomnusWu** [comment]
主要是控制点击事件。
