### ISSUE TITLE
MonthView 怎样增加上月、下月的显示

### ISSUE THREAD

**Issue by foxsent** [dengshiwei/CalendarComponent#9]
MonthView 怎样增加上月、下月的显示

**Comment by andoter0501** [comment]
@foxsent 在本月中空白处补上上月或下月的日期，这个处于规划，还没开始开发

**Comment by foxsent** [comment]
我把空白处补全了，但是现在有的问题是，选中后，滑动到那一页有点卡顿，日历上绘制的事物多了也会出现卡顿
